### ISSUE TITLE
Layout causes duplicate duplicates

### ISSUE THREAD

**Issue by Luke-SF** [wpninjas/ninja-forms-layout-styles#151]
Duplicating a field within a form that has a layout, causes the element to be duplicated twice!

For example, set up a layout just like this, then try to duplicate any item:
http://imgur.com/a/HgQBm

**Comment by wpnzach** [comment]
@kstover @Luke-SF We can't reproduce this locally but we've seen this a few times.  Would you mind opening a ticket at https://ninjaforms.com/contact/ so we can have a more private discussion (we may ask for System Status and admin credentials if thats okay?)

**Comment by Quay3** [comment]
I've replicated this locally. It requires Multi-Part Forms and Layout and Styles both to be active on the site.

Steps to Reproduce:
1. Create or edit an existing form.
2. Duplicate a field on the form. At this point, you will see two of the same field, one right where it should go and the other appearing at the bottom of the page.
3. Try deleting the one at the bottom of the page and notice how it deletes the other inline one.
4. Try editing either one and note that it applies to the other as well.
5. Try previewing or publishing to view the results and notice that both are on the form.

**Comment by kjohnson** [comment]
@Quay3 Can you confirm that L&S and MP are up to date? This should have already been resolved. /cc @Much2tall

**Comment by Quay3** [comment]
Yes. Just pulled new copies down from my ninjaforms.com account. L&S 3.0.20 and MPF 3.0.18. Tested after another user reported this in a ticket this morning. He's using the same versions of both extensions as well.

**Comment by kstover** [comment]
@Quay3 @Luke-SF @kjohnson I just tested with latest MP and L&S. I can't replicate this behaviour at all. I've created a form with the same fields and format that Luke gave above, but duplicating results in just one field. @Quay3 When you are in the office next, can you show me this first-hand?

**Comment by wpnzach** [comment]
This is still hapenning.  I, @jameslaws and a user all confirmed it.  Replication Steps:

1. Create new form from blank template
2. Add a single line text field
3. Duplicate that field

**Comment by Quay3** [comment]
Another report:

https://wpninjas.kustomerapp.com/app/customers/599ebdac632e320012eb8a24/event/599ebdad632e320012eb8a26

**Comment by Much2tall** [comment]
Another report:

https://wpninjas.kustomerapp.com/app/customers/59b3babb469fa30012244a70/event/59b3babc469fa30012244a72

**Comment by Quay3** [comment]
Another report:

https://wpninjas.kustomerapp.com/app/customers/59ac34747cfab40010711e42/event/59b57d56469fa3001228f87d
