### ISSUE TITLE
Horizontal align problem

### ISSUE THREAD

**Issue by bdogan** [wpninjas/ninja-forms-layout-styles#166]
With last update of NinjaForms;

![e94b3f8d-7f53-4559-a2cd-827ae8d554df](https://user-images.githubusercontent.com/1773731/39294817-5f1dcca2-4945-11e8-89ec-adab61ccd11a.jpg)

Wordpress: 4.9.5–tr_TR
Theme: [TheFox](https://themeforest.net/item/thefox-responsive-multipurpose-wordpress-theme/11099136) - 3.3
NinjaForms version: 3.2.22. (with 3.2.14 no problem).
NinjaForms - Layout & Styles version: 3.0.25 

all are licensed

**Comment by wpnzach** [comment]
Cannot replicate, please reach out to our support team here: https://ninjaforms.com/contact/
